### ISSUE TITLE
Movement Counter to Home Assistant?

### ISSUE THREAD

**Issue by villevirtanen** [Scrin/RuuviBridge#3]
Great bridge to transfer data to Home Assistant. Thanks! However, one question. RuuviBridge decodes data from my RuuviTag like this:

```json
{
    "name": "Postilaatikko",
    "mac": "xx:x...",
    "timestamp": 1650901857,
    "data_format": 5,
    "temperature": 6.875,
    "humidity": 42.0975,
    "pressure": 100399,
    "accelerationX": -0.192,
    "accelerationY": -1.076,
    "accelerationZ": -0.076,
    "batteryVoltage": 3.016,
    "txPower": 4,
    "rssi": -84,
    "movementCounter": 114,
    "measurementSequenceNumber": 6553
}
```
But I can not find ruuvitag_MAC_movementCounter MQTT topic under homeassistant/sensor and probably for that reason I can find only these sensors in my Home Assistant:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/25028729/165127649-a23b5fad-b749-4f4a-8c81-db8d8c4f38b2.png">

I'd like to see the Movement counter data in Home Assistant. Is this a missing feature or something else maybe?

**Comment by Scrin** [comment]
Apparently I managed to forget the movement counter from the published HA discovery topics. It should be fixed now and a new release should be built in a few minutes
